local middle = require(script.Parent.Middle)
describe('middle', function()
    it('should return upon call', function()
        expect(middle).to.be.a('table')
        it('should include LoadPackage', function()
            expect(middle.LoadPackage).to.be.ok()
        end)
        it('should include LoadCommon', function()
            expect(middle.LoadCommon).to.be.ok()
        end)
    end)
end)